/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hello */

#ifndef _Included_Hello
#define _Included_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Hello
 * Method:    say
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Hello_say(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
